CREATE DATABASE IF NOT EXISTS esp32_database;
USE esp32_database;

-- USERS TABLE
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

-- ESP CODES TABLE
CREATE TABLE espcodes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    unique_code VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- OPTIONAL SENSOR LOGS
CREATE TABLE sensor_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    temperature FLOAT,
    setpoint FLOAT,
    rpm INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);